### ISSUE TITLE
Cannot proceed after "Ready to Commit"

### ISSUE THREAD

**Issue by ispiroglu** [stefanlogue/meteor#32]
### 🐛 Describe the bug

Hi, 

I've cloned the main branch and tried to build on my own using make. 

Either I build it with make or go build,  or just run it with go run, I could not continue after 'Ready to Commit' phase. 
The latest binary is on commit : #7f686a0, but the main branch is not working properly I think.

I've tracked down the commits and #refactor(deps): update dependencies the application started to fail after this commit. 

### Versions

main branch

**Comment by ispiroglu** [comment]
I will create a pull request to fix this.

**Comment by stefanlogue** [comment]
Thanks for raising this! I've done some investigating the root cause of the issue, and it was caused by an updated dependency changing it's API. 

I appreciate you taking the time to fix this in your PR by reverting the dependency updates, but I think I'm going to consume the new API correctly instead (something I should've done from the start!).
